### ISSUE TITLE
Integration of Prettier and ESLint for Code Quality Assurance and Consistency

### ISSUE THREAD

**Issue by kiochan** [ZenkieBear/glassmorphism#7]
In my opinion, the introduction of tools like Prettier or ESLint is essential for this project. These tools automate the enforcement of a unified coding style, thus streamlining the code submission process. By incorporating Prettier or ESLint into our workflow, we can eliminate inconsistencies in code formatting and reduce the time spent on manual code reviews. Furthermore, these tools can detect potential code errors, thereby enhancing the overall quality, readability, and maintainability of the codebase. Implementing such a structured approach towards code quality and uniformity is pivotal in maintaining a healthy and efficient development environment.

**Comment by ZacharyBear** [comment]
I will add linters and commit soon. 🚧
